# Generated by Django 3.2.7 on 2021-09-22 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 14, 19, 39, 689507, tzinfo=utc)),
        ),
    ]
