# Generated by Django 3.2.7 on 2021-09-22 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_contatos_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 14, 27, 20, 177349, tzinfo=utc)),
        ),
    ]
