# Generated by Django 3.2.7 on 2021-09-22 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20210922_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 22, 14, 27, 23, 985747, tzinfo=utc)),
        ),
    ]
